package NutriaApp;

import NutriaModel.NutrientConstraint;
import NutriaModel.NutrientConstraintsByNutSheetTableModel;
import NutriaModel.NutritionalSheet;
import NutriaModel.NutritionalSheetDaoImpl;
import java.sql.SQLException;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JDialog;

/**
 *
 * @author Ariel
 */
public class JPanelNutritionalSheetForm extends javax.swing.JPanel {

    /**
     * Creates new form JPanelNutritionalSheetForm
     */
    
    private NutritionalSheetDaoImpl nutritionalSheetDao;
    private Long nutritionalSheetId;
    private NutritionalSheet nutritionalSheet;
    private NutrientConstraintsByNutSheetTableModel constraintsByNutSheetTableModel;
    private JDialog container;
    private Boolean success = false;
    
    public JPanelNutritionalSheetForm(JDialog container) {
        this.container = container;
        initComponents();
        initCustomComponents();
    }
    
    public JPanelNutritionalSheetForm(JDialog container, Long nutritionalSheetId) {
        this.container = container;
        this.nutritionalSheetId = nutritionalSheetId;
        initComponents();
        initCustomComponents();
    }
    
    public Boolean getSuccess() {
        return this.success;
    }
    
    private void initCustomComponents() {
        try {
            nutritionalSheetDao = new NutritionalSheetDaoImpl();
            constraintsByNutSheetTableModel = new NutrientConstraintsByNutSheetTableModel();
            if(nutritionalSheetId != null) {
                nutritionalSheet = nutritionalSheetDao.queryForId(nutritionalSheetId);
                nutritionalSheetDao.populateNutritionalSheet(nutritionalSheet);
            } else {
                nutritionalSheet = new NutritionalSheet();
            }
            mappNutritionalSheetToForm();
        } catch(SQLException ex) {
            //TODO: handle initCustomComponents
            ex.printStackTrace();
        }
    }
    
    private void mappNutritionalSheetToForm() {
        jTextFieldNutritionalSheetName.setText(nutritionalSheet.getName());
        if(nutritionalSheet.getNutrientConstraintList() != null) {
            constraintsByNutSheetTableModel.setNutrientConstraintList(nutritionalSheet.getNutrientConstraintList());
        }
        jTableNutrientConstraints.setModel(constraintsByNutSheetTableModel);
        jTableNutrientConstraints.removeColumn(jTableNutrientConstraints.getColumn("id"));
        JComboBox minComboBox = new JComboBox();
        minComboBox.addItem(">=");
        minComboBox.addItem("=");
        jTableNutrientConstraints.getColumn("R1").setCellEditor(new DefaultCellEditor(minComboBox));
        
        JComboBox maxComboBox = new JComboBox();
        maxComboBox.addItem(null);
        maxComboBox.addItem("<=");
        maxComboBox.addItem("=");
        jTableNutrientConstraints.getColumn("R2").setCellEditor(new DefaultCellEditor(maxComboBox));
    }
    
    private void mappFormToNutritionalSheet() {
        nutritionalSheet.setName(jTextFieldNutritionalSheetName.getText());
        nutritionalSheet.setNutrientConstraintList(constraintsByNutSheetTableModel.getNutrientConstraintList());
    }
    
    private void processSave() {
        mappFormToNutritionalSheet();
        try {
            nutritionalSheetDao.createOrUpdate(nutritionalSheet);
            nutritionalSheetId = nutritionalSheet.getId();
            success = true;
        } catch(SQLException ex) {
            //TODO: handle ingredient save exception
            ex.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNutritionalSheetName = new javax.swing.JLabel();
        jPanelNutritionalConstraints = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNutrientConstraints = new javax.swing.JTable();
        jButtonAddNutrient = new javax.swing.JButton();
        jButtonRemoveNutrient = new javax.swing.JButton();
        jTextFieldNutritionalSheetName = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        jLabelNutritionalSheetName.setText("Nombre");

        jPanelNutritionalConstraints.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Restricciones Nutritionales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.black));

        jTableNutrientConstraints.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(jTableNutrientConstraints);

        jButtonAddNutrient.setText("Agregar Nutriente");
        jButtonAddNutrient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddNutrientActionPerformed(evt);
            }
        });

        jButtonRemoveNutrient.setText("Quitar Nutriente");
        jButtonRemoveNutrient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveNutrientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNutritionalConstraintsLayout = new javax.swing.GroupLayout(jPanelNutritionalConstraints);
        jPanelNutritionalConstraints.setLayout(jPanelNutritionalConstraintsLayout);
        jPanelNutritionalConstraintsLayout.setHorizontalGroup(
            jPanelNutritionalConstraintsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNutritionalConstraintsLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButtonAddNutrient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRemoveNutrient)
                .addGap(63, 63, 63))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNutritionalConstraintsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanelNutritionalConstraintsLayout.setVerticalGroup(
            jPanelNutritionalConstraintsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNutritionalConstraintsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNutritionalConstraintsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddNutrient)
                    .addComponent(jButtonRemoveNutrient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonSave.setText("Guardar");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancelar");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelNutritionalSheetName)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldNutritionalSheetName, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelNutritionalConstraints, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jButtonSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancel)
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNutritionalSheetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNutritionalSheetName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelNutritionalConstraints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddNutrientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddNutrientActionPerformed
        JDialog findNutrientDialog = new JDialog(container, "Buscar Nutriente", true);
        JPanelFindNutrient findNutrient = new JPanelFindNutrient(findNutrientDialog);
        findNutrientDialog.setContentPane(findNutrient);
        findNutrientDialog.setSize(500, 500);
        findNutrientDialog.setResizable(false);
        findNutrientDialog.setVisible(true);
        if (findNutrient.getSelectedNutrient() != null) {
            System.out.println("Successfully got nutrientId");
            constraintsByNutSheetTableModel.getNutrientConstraintList().add(
                    new NutrientConstraint(findNutrient.getSelectedNutrient()
                ));
            constraintsByNutSheetTableModel.fireTableDataChanged();
        }
    }//GEN-LAST:event_jButtonAddNutrientActionPerformed

    private void jButtonRemoveNutrientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveNutrientActionPerformed
        int rowIndex = jTableNutrientConstraints.getSelectedRow();
        NutrientConstraint toRemove = (NutrientConstraint)constraintsByNutSheetTableModel.getObjectAtRow(rowIndex);
        constraintsByNutSheetTableModel.getNutrientConstraintList().remove(toRemove);
        constraintsByNutSheetTableModel.fireTableDataChanged();
    }//GEN-LAST:event_jButtonRemoveNutrientActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        processSave();
        if(success) {
            container.setVisible(false);
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        container.setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddNutrient;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonRemoveNutrient;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabelNutritionalSheetName;
    private javax.swing.JPanel jPanelNutritionalConstraints;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableNutrientConstraints;
    private javax.swing.JTextField jTextFieldNutritionalSheetName;
    // End of variables declaration//GEN-END:variables
}
