package NutriaApp;

import NutriaModel.Nutrient;
import NutriaModel.NutrientDaoImpl;
import NutriaModel.NutrientTableModel;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;

/**
 *
 * @author Ariel
 */
public class JPanelFindNutrient extends javax.swing.JPanel {

    /**
     * Creates new form JPanelFindNutrient
     */
    private Nutrient selectedNutrient;
    private NutrientTableModel nutrientTableModel;
    private NutrientDaoImpl nutrientDao;
    private List<Nutrient> originalNutrientList;
    private JDialog container;
    private static Long lastTimePressed;
    
    public JPanelFindNutrient(JDialog container) {
        this.container = container;
        initComponents();
        initCustomComponents();
    }
    
    public void initCustomComponents() {
        try {
            nutrientDao = new NutrientDaoImpl();
            nutrientTableModel = new NutrientTableModel();
            originalNutrientList = nutrientDao.queryForAll();
            nutrientTableModel.setNutrientList(originalNutrientList);
            jTableResultNutrients.setModel(nutrientTableModel);
            jTableResultNutrients.removeColumn(jTableResultNutrients.getColumn("id"));
            lastTimePressed = System.currentTimeMillis();
        } catch(SQLException ex) {
            //TODO: handle initCustomComponents
        }
    }
    
    public Nutrient getSelectedNutrient() {
        return this.selectedNutrient;
    }
    
    private void findNutrient(String text) {
        List<Nutrient> nutrientList = originalNutrientList;
        List<Nutrient> filteredNutrientList = new ArrayList<>();
        for(Nutrient nutrient : nutrientList) {
            if(nutrient.getName().toLowerCase().contains(text.toLowerCase())) {
               filteredNutrientList.add(nutrient);
            }
        }
        nutrientTableModel.setNutrientList(filteredNutrientList);
        nutrientTableModel.fireTableDataChanged();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldFindNutrient = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableResultNutrients = new javax.swing.JTable();
        jButtonSelectNutrient = new javax.swing.JButton();
        jLabelFindNutrient = new javax.swing.JLabel();
        jLabelNotFoundTip = new javax.swing.JLabel();
        jLabelNewNutrientTip = new javax.swing.JLabel();
        jLabelLinkNewNutrient = new javax.swing.JLabel();

        jTextFieldFindNutrient.setToolTipText("Escriba el nombre del nutriente a buscar");
        jTextFieldFindNutrient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldFindNutrientKeyReleased(evt);
            }
        });

        jTableResultNutrients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(jTableResultNutrients);

        jButtonSelectNutrient.setText("Seleccionar");
        jButtonSelectNutrient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectNutrientActionPerformed(evt);
            }
        });

        jLabelFindNutrient.setText("Buscar: ");

        jLabelNotFoundTip.setText("No encuentras el nutriente que buscas?");

        jLabelNewNutrientTip.setText("Agrega uno nuevo");

        jLabelLinkNewNutrient.setForeground(new java.awt.Color(0, 51, 255));
        jLabelLinkNewNutrient.setText("<html>\n<body>\n<u>aquí.<u>\n</body>\n</html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelFindNutrient)
                        .addGap(22, 22, 22)
                        .addComponent(jTextFieldFindNutrient, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabelNotFoundTip))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jButtonSelectNutrient))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabelNewNutrientTip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelLinkNewNutrient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFindNutrient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFindNutrient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSelectNutrient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelNotFoundTip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNewNutrientTip)
                    .addComponent(jLabelLinkNewNutrient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldFindNutrientKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFindNutrientKeyReleased
        findNutrient(jTextFieldFindNutrient.getText());
    }//GEN-LAST:event_jTextFieldFindNutrientKeyReleased

    private void jButtonSelectNutrientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectNutrientActionPerformed
        int rowIndex = jTableResultNutrients.getSelectedRow();
        selectedNutrient = (Nutrient)nutrientTableModel.getObjectAtRow(rowIndex);
        container.setVisible(false);
    }//GEN-LAST:event_jButtonSelectNutrientActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSelectNutrient;
    private javax.swing.JLabel jLabelFindNutrient;
    private javax.swing.JLabel jLabelLinkNewNutrient;
    private javax.swing.JLabel jLabelNewNutrientTip;
    private javax.swing.JLabel jLabelNotFoundTip;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableResultNutrients;
    private javax.swing.JTextField jTextFieldFindNutrient;
    // End of variables declaration//GEN-END:variables
}
